# Generated by Django 4.1.3 on 2022-12-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_creator_course_author'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creator',
            new_name='Author',
        ),
    ]
