# Generated by Django 4.1.3 on 2023-02-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
    ]
